@echo off
echo Stopping Docker container...
docker stop alveuscontroller

echo Removing Docker container...
docker rm alveuscontroller

echo Removing unused Docker images (force)...
docker image prune -a -f

echo Starting a clean Docker build...
docker compose up --build -d