'use strict';

// temp file just to leave config.js alone for now

const groups = /** @type {const} */ ({
  admin: 0,
  superUser: 1,
  mod: 2,
  operator: 3,
  vip: 4,
  user: 5
})

/**
 * @type {Record<string, import('./types.d.ts').Group>}
 */
const groupMemberships = {
  "spacevoyage": 'admin',
  "maya": 'admin',
  "theconnorobrien": 'admin',
  "alveussanctuary": 'admin',

  "ellaandalex": 'superUser',
  "dionysus1911": 'superUser',
  "dannydv": 'superUser',
  "maxzillajr": 'superUser',
  "illjx": 'superUser',
  "kayla_alveus": 'superUser',
  "alex_b_patrick": 'superUser',
  "lindsay_alveus": 'superUser',
  "strickknine": 'superUser',
  "tarantulizer": 'superUser',
  "spiderdaynightlive": 'superUser',
  "srutiloops": 'superUser',
  "evantomology": 'superUser',
  "amanda2815": 'superUser',

  "96allskills": 'mod',
  "dansza": 'mod',
  "echoskope": 'mod',
  "loganrx_": 'mod',
  "mattipv4": 'mod',
  "mik_mwp": 'mod',
  "pjeweb": 'mod',
  "shrezno": 'mod',

  "stolenarmy_": 'operator',
  "berlac": 'operator',
  "merger3": 'operator',
  "nitelitedf": 'operator',
  "fixterjake14": 'operator',
  "purplemartinconservation": 'operator',
  "wazix11": 'operator',
  "lazygoosepxls": 'operator',
  "alxiszzz": 'operator',
  "shutupleonard": 'operator',
  "taizun": 'operator',
  "lumberaxe1": 'operator',
  "glennvde": 'operator',
  "wolfone_": 'operator',
  "dohregard": 'operator',
  "lakel1": 'operator',
  "darkrow_": 'operator',
  "minipurrl": 'operator',
  "gnomechildboi": 'operator',
  "danman149": 'operator',
  "hunnybeehelen": 'operator',
  "strangecyan": 'operator',
  "viphippo": 'operator',
  "bagel_deficient": 'operator',
  "rhinofriend": 'operator',
  "ponchobee": 'operator',
  "orophia": 'operator',

  "tfries_": 'vip',
  "sivvii_": 'vip',
  "ghandii_": 'vip',
  "axialmars": 'vip',
  "jazz_peru": 'vip',
  "stealfydoge": 'vip',
  "xano218": 'vip',
  "experimentalcyborg": 'vip',
  "klav___": 'vip',
  "monkarooo": 'vip',
  "nixxform": 'vip',
  "madcharliekelly": 'vip',
  "josh_raiden": 'vip',
  "jateu": 'vip',
  "storesE6": 'vip',
  "rebecca_h9": 'vip',
  "matthewde": 'vip',
  "user_11_11": 'vip',
  "huniebeexd": 'vip',
  "kurtyykins": 'vip',
  "breacherman": 'vip',
  "bryceisrightjr": 'vip',
  "sumaxu": 'vip',
  "mariemellie": 'vip',
  "ewok_626": 'vip',
  "quokka64": 'vip',
  "nov1cegg": 'vip',
  "casualruffian": 'vip',
  "likethecheesebri": 'vip',
  "otsargh": 'vip',
  "just_some_donkus": 'vip',
  "fiveacross": 'vip',
  "itszalndrin": 'vip',
  "ohnonicoleio": 'vip',
  "fishymeep": 'vip'
}

module.exports = {
  groups,
  groupMemberships,
}
