// @ts-check

// temp file just to leave config.js alone for now

const groups = /** @type {const} */ ({
  admin: 0,
  superUser: 1,
  mod: 2,
  operator: 3,
  vip: 4,
  user: 5
})

/**
 * @type {Record<string, import('./types.d.ts').Group>}
 */
const groupMemberships = {
  "spacevoyage": 'admin',
  "maya": 'admin',
  "theconnorobrien": 'admin',
  "alveussanctuary": 'admin',

  "ellaandalex": 'superUser',
  "dionysus1911": 'superUser',
  "dannydv": 'superUser',
  "maxzillajr": 'superUser',
  "illjx": 'superUser',
  "kayla_alveus": 'superUser',
  "alex_b_patrick": 'superUser',
  "lindsay_alveus": 'superUser',
  "strickknine": 'superUser',
  "tarantulizer": 'superUser',
  "spiderdaynightlive": 'superUser',
  "srutiloops": 'superUser',
  "evantomology": 'superUser',
  "amanda2815": 'superUser',

  "96allskills": 'mod',
  "dansza": 'mod',
  "echoskope": 'mod',
  "loganrx_": 'mod',
  "mattipv4": 'mod',
  "mik_mwp": 'mod',
  "pjeweb": 'mod',
  "shrezno": 'mod',

  "stolenarmy_": 'operator',
  "berlac": 'operator',
  "merger3": 'operator',
  "nitelitedf": 'operator',
  "fixterjake14": 'operator',
  "purplemartinconservation": 'operator',
  "wazix11": 'operator',
  "lazygoosepxls": 'operator',
  "alxiszzz": 'operator',
  "shutupleonard": 'operator',
  "taizun": 'operator',
  "lumberaxe1": 'operator',
  "glennvde": 'operator',
  "wolfone_": 'operator',
  "dohregard": 'operator',
  "lakel1": 'operator',
  "darkrow_": 'operator',
  "minipurrl": 'operator',
  "gnomechildboi": 'operator',
  "danman149": 'operator',
  "hunnybeehelen": 'operator',
  "strangecyan": 'operator',
  "viphippo": 'operator',
  "bagel_deficient": 'operator',
  "rhinofriend": 'operator',
  "ponchobee": 'operator',
  "orophia": 'operator',

  "tfries_": 'vip',
  "sivvii_": 'vip',
  "ghandii_": 'vip',
  "axialmars": 'vip',
  "jazz_peru": 'vip',
  "stealfydoge": 'vip',
  "xano218": 'vip',
  "experimentalcyborg": 'vip',
  "klav___": 'vip',
  "monkarooo": 'vip',
  "nixxform": 'vip',
  "madcharliekelly": 'vip',
  "josh_raiden": 'vip',
  "jateu": 'vip',
  "storesE6": 'vip',
  "rebecca_h9": 'vip',
  "matthewde": 'vip',
  "user_11_11": 'vip',
  "huniebeexd": 'vip',
  "kurtyykins": 'vip',
  "breacherman": 'vip',
  "bryceisrightjr": 'vip',
  "sumaxu": 'vip',
  "mariemellie": 'vip',
  "ewok_626": 'vip',
  "quokka64": 'vip',
  "nov1cegg": 'vip',
  "casualruffian": 'vip',
  "likethecheesebri": 'vip',
  "otsargh": 'vip',
  "just_some_donkus": 'vip',
  "fiveacross": 'vip',
  "itszalndrin": 'vip',
  "ohnonicoleio": 'vip',
  "fishymeep": 'vip'
}

// /**
//  * @type {Record<import('./types.d.ts').Group, Array<string>>}
//  */
// const groupMemberships = {
//   admin: [
//     "spacevoyage",
//     "maya",
//     "theconnorobrien",
//     "alveussanctuary"
//   ],
//   superUser: [
//     "ellaandalex",
//     "dionysus1911",
//     "dannydv",
//     "maxzillajr",
//     "illjx",
//     "kayla_alveus",
//     "alex_b_patrick",
//     "lindsay_alveus",
//     "strickknine",
//     "tarantulizer",
//     "spiderdaynightlive",
//     "srutiloops",
//     "evantomology",
//     "amanda2815"
//   ],
//   mod: [
//     "96allskills",
//     "dansza",
//     "echoskope",
//     "loganrx_",
//     "mattipv4",
//     "mik_mwp",
//     "pjeweb",
//     "shrezno"
//   ],
//   operator: [
//     "stolenarmy_",
//     "berlac",
//     "merger3",
//     "nitelitedf",
//     "fixterjake14",
//     "purplemartinconservation",
//     "wazix11",
//     "lazygoosepxls",
//     "alxiszzz",
//     "shutupleonard",
//     "taizun",
//     "lumberaxe1",
//     "glennvde",
//     "wolfone_",
//     "dohregard",
//     "lakel1",
//     "darkrow_",
//     "minipurrl",
//     "gnomechildboi",
//     "danman149",
//     "hunnybeehelen",
//     "strangecyan",
//     "viphippo",
//     "bagel_deficient",
//     "rhinofriend",
//     "ponchobee",
//     "orophia"
//   ],
//   vip: [
//     "tfries_",
//     "sivvii_",
//     "ghandii_",
//     "axialmars",
//     "jazz_peru",
//     "stealfydoge",
//     "xano218",
//     "experimentalcyborg",
//     "klav___",
//     "monkarooo",
//     "nixxform",
//     "madcharliekelly",
//     "josh_raiden",
//     "jateu",
//     "storesE6",
//     "rebecca_h9",
//     "matthewde",
//     "user_11_11",
//     "huniebeexd",
//     "kurtyykins",
//     "breacherman",
//     "bryceisrightjr",
//     "sumaxu",
//     "mariemellie",
//     "ewok_626",
//     "quokka64",
//     "nov1cegg",
//     "casualruffian",
//     "likethecheesebri",
//     "otsargh",
//     "just_some_donkus",
//     "fiveacross",
//     "itszalndrin",
//     "ohnonicoleio",
//     "fishymeep"
//   ],
//   user: []
// }

module.exports = {
  groups,
  groupMemberships,
}
